version: '3.5'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    ports:
    - 1433:1433
environment:
  - MSSQL_SA_PASSWORD=12345
  - ACCEPT_EULA=Y
  - MSSQL_PID=Developer
mysql:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=12345

